name = "hugo_theme_travis"
license = "MIT"
licenselink = "https://github.com/traviskn/hugo_theme_travis/blob/master/LICENSE.md"
description = "A simple theme for my personal hugo blog"
homepage = "http://traviskn.github.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.21

[author]
  name = "Travis Nuttall"
  homepage = "http://traviskn.github.io"
